accounts/urls.py
from accounts import views
from django.urls import path
from django.urls import include


urlpatterns = [
    path(
        "customer/account/",
        include(
            (
                [
                    path(
                        route="signup/",
                        view=views.account_signup_view,
                        name="account_signup",
                    ),
                    path(
                        route="login/",
                        view=views.account_login_view,
                        name="account_login",
                    ),
                    path(
                        route="reset-password/",
                        view=views.account_request_password_reset_view,
                        name="account_reset_password",
                    ),
                    path(
                        route="reset-password/<uidb64>/<token>/",
                        view=views.account_request_password_reset_view,
                        name="account_reset_password",
                    ),
                    path(
                        route="set-new-password/<uidb64>/<token>/",
                        view=views.account_set_new_password_view,
                        name="set_new_password",
                    ),
                    path(
                        route="logout/",
                        view=views.account_logout_view,
                        name="account_logout",
                    ),
                ],
                "accounts",
            ),
            namespace="auth_views",
        ),
    ),
    path(
        "customer/",
        include(
            (
                [
                    path(
                        route="account/index/",
                        view=views.dashboard_view,
                        name="profile",
                    ),
                    path(
                        route="order/index/",
                        view=views.order_list_view,
                        name="order_list",
                    ),
                    path(
                        route="order/detail/<int:pk>/",
                        view=views.order_detail_view,
                        name="order_detail",
                    ),
                    path(
                        route="settings/<str:slug>/",
                        view=views.settings_view,
                        name="update",
                    ),
                ],
                "accounts",
            ),
            namespace="dashboard_users",
        ),
    ),
    path(
        "sp-marketplace-delivery/",
        include(
            (
                [
                    path(
                        route="register/",
                        view=views.distributor_register_view,
                        name="delivery_register",
                    ),
                    path(
                        route="success/<int:delivery_id>/",
                        view=views.distributor_register_success_view,
                        name="delivery_register_success",
                    ),
                ],
                "accounts",
            ),
            namespace="delivery",
        ),
    ),
]

checkout/urls.py
from checkout import views
from django.urls import path


app_name = "checkout"
urlpatterns = [
    path(route="", view=views.show_checkout, name="checkout"),
    path(
        route="success/<int:order_id>",
        view=views.order_success_view,
        name="order_success",
    ),
    path(
        route="check/status-order/", view=views.track_order_view, name="order_tracking"
    ),
    path(
        route="download-invoice/<int:order_id>/",
        view=views.download_invoice_view,
        name="download_invoice",
    ),
]

core/urls.py
from core.sitemap import SITEMAPS
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.models import Group
from django.contrib.sitemaps import views
from django.contrib.sites.models import Site
from django.shortcuts import render
from django.urls import include
from django.urls import path
from django.views.generic import TemplateView
from django_summernote.models import Attachment
from search.views import search_view

admin.site.unregister(Site)
admin.site.unregister(Group)
admin.site.unregister(Attachment)


def handler404(request, exception, template_name="404.html"):
    return render(
        request,
        template_name=template_name,
        status=404,
        context={"page_title": "Page non trouvée"},
    )


def handler403(request, exception, template_name="403.html"):
    return render(
        request,
        template_name=template_name,
        status=403,
        context={"page_title": "Page non trouvée"},
    )


def handler500(request, template_name="500.html"):
    return render(
        request,
        template_name=template_name,
        status=500,
        context={"page_title": "Erreur interne"},
    )


urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path("sp-", include("pages.urls", namespace="pages")),
    path("checkout/", include("checkout.urls", namespace="checkout")),
    path(route="catalog/", view=search_view, name="search"),
    path("", include("catalogue.urls")),
    path("jet/", include("jet.urls", "jet")),
    path("summernote/", include("django_summernote.urls")),
    path("", include("accounts.urls")),
    path("", include("pwa.urls")),
    path(
        "sitemap.xml",
        views.sitemap,
        {"sitemaps": SITEMAPS},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = handler404
handler403 = handler403
handler201600 = handler500

admin.site.site_header = "LAREGINA DEALS ADMIN"
admin.site.site_title = "LAREGINA DEALS ADMIN"

if settings.DEBUG:
    urlpatterns += [
        path("404", handler404, {"exception": Exception()}),
        path("403", handler403, {"exception": Exception()}),
        path("500", handler500),
    ]

pages/urls.py
from django.conf import settings
from django.urls import path
from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView
from pages.views import contact_view

CACHE_TTL = getattr(settings, "CACHE_TTL", settings.CACHE_TIMEOUT)

app_name = "pages"
urlpatterns = [
    path(route="contactez-nous/", view=contact_view, name="contact"),
    path(
        "qui-sommes-nous/",
        cache_page(CACHE_TTL)(
            TemplateView.as_view(
                extra_context={
                    "page_title": "À propos de nous",
                    "page_description": "Qui sommes-nous ?",
                },
                template_name="pages/about-us.html",
            )
        ),
        name="about-us",
    ),
    path(
        "questions-frequement-posees/",
        cache_page(CACHE_TTL)(
            TemplateView.as_view(
                extra_context={
                    "page_title": "FAQs : Questions fréquemment posées",
                    "page_description": "Questions fréquemment posées",
                },
                template_name="pages/faqs.html",
            )
        ),
        name="faqs",
    ),
    path(
        "condition-generale-utilisation/",
        cache_page(CACHE_TTL)(
            TemplateView.as_view(
                extra_context={
                    "page_title": "Conditions Générales d'Utilisation",
                    "page_description": "Conditions Générales d'Utilisation",
                },
                template_name="pages/cgu.html",
            )
        ),
        name="cgu",
    ),
    path(
        "politique-de-confidentialite/",
        cache_page(CACHE_TTL)(
            TemplateView.as_view(
                extra_context={
                    "page_title": "Politique de Confidentialité",
                    "page_description": "Politique de Confidentialité",
                },
                template_name="pages/policy.html",
            )
        ),
        name="policy",
    ),
    path(
        "politique-de-retour/",
        cache_page(CACHE_TTL)(
            TemplateView.as_view(
                extra_context={
                    "page_title": "Politique de retour",
                    "page_description": "Politique de retour",
                },
                template_name="pages/return.html",
            )
        ),
        name="return",
    ),
]

checkout/models.py
import datetime
import decimal
import random
import string

from catalogue.models import Product
from checkout.managers import OrderManager
from django.contrib import admin
from django.db import models
from django.urls import reverse
from helpers.models import BaseOrderInfo
from helpers.models import BaseTimeStampModel


NULL_AND_BLANK = {"null": True, "blank": True}


class Order(BaseOrderInfo, BaseTimeStampModel):
    SHIPPED = "commande livrée"
    CANCELLED = "commande annulée"
    PROCESSED = "livraison en cours"
    SUBMITTED = "traitement en cours"

    ORDER_STATUS = (
        (SHIPPED, "commande livrée"),
        (CANCELLED, "commande annulée"),
        (SUBMITTED, "traitement en cours"),
        (PROCESSED, "livraison en cours"),
    )

    NOW_PAYMENT = 1
    DELIVERY_PAYMENT = 0
    DEFAULT_PAYMENT = NOW_PAYMENT

    TYPES_PAYMENT_CHOICES = (
        (NOW_PAYMENT, "PAYER CASH"),
        (DELIVERY_PAYMENT, "PAYER À LA LIVRAISON"),
    )

    status = models.CharField(
        verbose_name="status", max_length=120, choices=ORDER_STATUS, default=SUBMITTED
    )
    payment = models.PositiveIntegerField(
        default=DEFAULT_PAYMENT,
        choices=TYPES_PAYMENT_CHOICES,
        verbose_name="Type de paiment",
    )
    transaction_id = models.CharField(
        verbose_name="id de la commande", unique=True, max_length=20, **NULL_AND_BLANK
    )
    ip_address = models.CharField(
        verbose_name="adresse ip", max_length=50, **NULL_AND_BLANK
    )
    emailing = models.BooleanField(
        verbose_name="abonnement aux offres et promotions", default=False
    )
    collecte_data = models.BooleanField(
        verbose_name="Message de satisfaction envoyé", default=False
    )
    date = models.DateTimeField(verbose_name="date de la commade", auto_now_add=True)
    last_updated = models.DateTimeField(
        verbose_name="derniere modification", auto_now=True
    )
    distributor = models.ForeignKey(
        to="accounts.DistributorCustomer",
        on_delete=models.CASCADE,
        limit_choices_to={"active": True},
        related_name="distibutors",
        verbose_name="livreur",
        help_text="Choisir un livreur",
        **NULL_AND_BLANK,
    )
    objects = OrderManager()

    class Meta:
        verbose_name_plural = "Payer Cash"
        indexes = [models.Index(fields=["id"])]

    def __str__(self):
        return f"#{self.transaction_id} - {self.status}"

    @admin.display(description="n° commande")
    def get_order_id(self):
        return self.transaction_id

    @admin.display(description="téléphone")
    def get_phone_number(self):
        return self.phone

    @admin.display(description="nom")
    def get_short_name(self):
        return self.shipping_first_name

    @admin.display(description="nom & prénoms")
    def get_full_name(self):
        return f"{self.get_short_name()} {self.shipping_last_name}"

    @admin.display(description="adresse de livraison")
    def get_shipping_delivery(self):
        return f"{self.shipping_country}, {self.shipping_city}, {self.shipping_adress} | {self.phone}"

    def get_shipping_delivery_for_seller(self):
        return f"{self.shipping_city}, {self.shipping_country}"

    def save(self, *args, **kwargs):
        if self.transaction_id is None:
            self.generate(8)
        super().save(*args, **kwargs)

    def generate(self, nb_carac):
        today = datetime.date.today().strftime("%d%m%y")
        carac = string.digits
        random_carac = [random.choice(carac) for _ in range(nb_carac)]
        self.transaction_id = "{}".format(today + "".join(random_carac))

    def order_items(self):
        order_items = OrderItem.objects.filter(order=self)
        return order_items

    @admin.display(description="montant commande")
    def get_order_total(self):
        total = decimal.Decimal("0")
        for item in self.order_items():
            total += item.total
        return total

    @admin.display(description="montant réglé")
    def get_order_payment(self):
        order_total = self.get_order_total()
        payment_advance = int("0")
        min_amount = int("10000")
        percent_amount = decimal.Decimal("0.5")
        if order_total >= min_amount:
            payment_advance = order_total * percent_amount
        elif order_total <= min_amount:
            payment_advance = order_total
        return payment_advance

    @admin.display(description="reste à payé")
    def get_order_rest_payment(self):
        payment_rest = int("0")
        order_total = self.get_order_total()
        order_advance = self.get_order_payment()
        payment_rest = float(order_total - order_advance)
        return payment_rest

    @admin.display(description="cash du vendeur")
    def total_seller_order(self):
        total_se_ = self.get_order_total()
        return total_se_

    @admin.display(description="commission")
    def get_cost(self):
        percent = decimal.Decimal("0.05")
        cost = self.total_seller_order() * percent
        return cost

    @admin.display(description="coût total")
    def total_order(self):
        total_or_ = self.total_seller_order() - self.get_cost()
        return total_or_

    @admin.display(description="cash total")
    def get_total_sales(self):
        total = decimal.Decimal(0)
        orders = self.order_items()
        for item in orders:
            total += item.total_order()
        return total

    def get_absolute_url(self):
        return reverse("dashboard_seller:order_detail", kwargs={"pk": int(self.id)})

    def get_success_url(self):
        return reverse(
            "checkout:order_success", kwargs={"pk": int(self.transaction_id)}
        )


class OrderCashOnDelivery(Order):
    class Meta:
        proxy = True
        verbose_name_plural = "Payer à la livraison"


class OrderShipped(Order):
    class Meta:
        proxy = True
        verbose_name_plural = "Commandes livrées"


class OrderCancelled(Order):
    class Meta:
        proxy = True
        verbose_name_plural = "Commandes annulées"


class OrderItem(models.Model):
    order = models.ForeignKey(
        to="checkout.Order",
        on_delete=models.CASCADE,
        related_name="orders",
        verbose_name="commande",
    )
    product = models.ForeignKey(
        to=Product,
        on_delete=models.CASCADE,
        related_name="products",
        verbose_name="produit",
    )
    quantity = models.IntegerField(verbose_name="quantité", default=1)
    date_updated = models.DateTimeField(
        verbose_name="derniere modification", auto_now=True, auto_now_add=False
    )
    date_created = models.DateTimeField(
        verbose_name="date ajout", auto_now=True, auto_now_add=False
    )

    class Meta:
        db_table = "checkout_order_item_db"
        ordering = ["-date_created", "-date_updated"]
        get_latest_by = ["-date_created", "-date_updated"]
        verbose_name_plural = "panier"
        indexes = [models.Index(fields=["id"])]

    def __str__(self):
        return self.product.name

    @property
    def total(self):
        return self.quantity * self.get_product_price()

    @admin.display(description="prix unitaire")
    def get_product_price(self):
        return self.product.get_product_price()

    @admin.display(description="produit")
    def get_product_name(self):
        return self.product.name

    @admin.display(description="N° de téléphone")
    def get_phone_number(self):
        return self.product.get_product_contact()

    @admin.display(description="contact boutique")
    def get_store_product(self):
        return f"{self.product.user.store} | {self.get_phone_number()}"

    @admin.display(description="boutique")
    def get_store_name(self):
        return self.product.user.store

    def get_absolute_url(self):
        return self.product.get_absolute_url()

templates/checkout/checkout_success.html
{% extends "base.html" %}
{% load humanize catalogue_tags %}


{% block content %}
{% url 'checkout:order_tracking' as order_tracking %}
{% url 'catalogue:product_list' as product_list %}
{% url 'checkout:download_invoice' object.id as print_invoice %}

{% include "includes/partials/_partials_breadcrumb.html" %}

<section class="ps-section--account ps-checkout">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <div class="ps-section__header">
                    <h4 class="text-success">
                        Commande validée ! &smid; N° commande
                        {{ object.get_order_id }}
                    </h4>

                    <div class="ps-block--payment-method mb-0">
                        <span class='font-weight-bold'>
                            NB: Veuillez garder ce numéro ({{ object.transaction_id  }})
                            pour le retrait de votre commande.
                        </span>
                    </div>
                </div>

                <div class="ps-section__content card p-4">
                    <div class="row">
                        <div class="col-md-4 col-12">
                            <figure class="ps-block--invoice">
                                <figcaption>Nom &amp; prénom</figcaption>
                                <div class="ps-block__content">
                                    <strong>{{ object.get_full_name|upper }}</strong>
                                    <p>
                                        <strong>Email:</strong>:
                                        {{ object.email }}
                                    </p>
                                    <p><strong>Téléphone</strong>: {{ object.phone }}</p>
                                </div>
                            </figure>
                        </div>

                        <div class="col-md-4 col-12">
                            <figure class="ps-block--invoice">
                                <figcaption>Adresse de livraison</figcaption>
                                <div class="ps-block__content">
                                    <p>{{ object.get_shipping_delivery|linebreaksbr }}</p>
                                </div>
                            </figure>
                        </div>

                        <div class="col-md-4 col-12">
                            <figure class="ps-block--invoice">
                                <figcaption>Moyen de paiement</figcaption>
                                <div class="ps-block__content">
                                    <p>
                                        <strong>Methode: </strong>
                                        {{ object.get_payment_display }}
                                    </p>
                                    <p>
                                        <strong>Total</strong>:
                                        {{ object.get_order_total|intcomma }} Fr
                                    </p>
                                </div>
                            </figure>
                        </div>
                    </div>
                </div>

                <p class="text-muted py-3">
                    <span>Votre commande vous sera livrée dans 07 jours maximum.</span>
                    <span>Merci pour votre commande.</span>
                </p>

                <div class="ps-section__footer mt-3">
                    <div class="row">
                        <div class="col-4 float-left">
                            <a class="ps-btn ps-btn--sm text-uppercase font-weight-normal" href="{{ product_list }}">Continuer vos achats
                                <i class="icon-arrow-right"></i></a>
                        </div>

                        <div class="col-4">
                            <a class="btn ps-btn--sm text-uppercase font-weight-normal" href="{{ print_invoice }}"><i class="icon-printer"></i>
                                Imprimer le réçu.</a>
                        </div>

                        <div class="col-4 float-right">
                            <a class="ps-btn ps-btn--sm text-uppercase font-weight-normal" href="{{ order_tracking }}">suivre votre commande</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}