catalogue/urls.py
from cart.views import shopcart
from catalogue import views as catalogue_views
from category.views import category_detail_view
from django.urls import include
from django.urls import path
from pages import views as pages_views


urlpatterns = [
    path(route="", view=catalogue_views.home_view, name="home"),
    path(
        "cart/index/",
        include(
            (
                [
                    path(route="", view=shopcart, name="cart"),
                ],
                "catalogue",
            ),
            "cart",
        ),
    ),
    path(
        "",
        include(
            (
                [
                    path(
                        route="produit/",
                        view=catalogue_views.product_list_view,
                        name="product_list",
                    ),
                    path(
                        route="ps-<str:slug>-<int:pk>/",
                        view=catalogue_views.show_product,
                        name="product_detail",
                    ),
                ],
                "catalogue",
            ),
            namespace="catalogue",
        ),
    ),
    path(
        "",
        include(
            (
                [
                    path(
                        route="<str:slug>/",
                        view=category_detail_view,
                        name="category_detail",
                    ),
                ],
                "catalogue",
            ),
            "category",
        ),
    ),
    path(
        "avis-cliens/",
        include(
            (
                [
                    path(
                        route="<str:slug>/",
                        view=catalogue_views.add_review,
                        name="add_product_review",
                    ),
                ],
                "catalogue",
            ),
            namespace="reviews",
        ),
    ),
    path(
        "promotion/",
        include(
            (
                [
                    path(
                        route="<str:slug>/",
                        view=pages_views.promotion_detail,
                        name="promotion_detail",
                    ),
                    path(
                        route="destockages/list/",
                        view=pages_views.destockage_list_view,
                        name="promotion_destockage_list",
                    ),
                    path(
                        route="flash-sales/list/",
                        view=pages_views.sales_flash_list_view,
                        name="promotion_sales_flash_list",
                    ),
                    path(
                        route="nouveautes/list/",
                        view=pages_views.news_arrivals_list_view,
                        name="promotion_news_arrival_list",
                    ),
                ],
                "catalogue",
            ),
            namespace="promotion",
        ),
    ),
]

checkout/urls.py
from checkout import views
from django.urls import path


app_name = "checkout"
urlpatterns = [
    path(route="", view=views.show_checkout, name="checkout"),
    path(
        route="success/<int:order_id>",
        view=views.order_success_view,
        name="order_success",
    ),
    path(
        route="check/status-order/", view=views.track_order_view, name="order_tracking"
    ),
    path(
        route="download-invoice/<int:order_id>/",
        view=views.download_invoice_view,
        name="download_invoice",
    ),
]

core/urls.py
from core.sitemap import SITEMAPS
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.models import Group
from django.contrib.sitemaps import views
from django.contrib.sites.models import Site
from django.shortcuts import render
from django.urls import include
from django.urls import path
from django.views.generic import TemplateView
from django_summernote.models import Attachment
from search.views import search_view

admin.site.unregister(Site)
admin.site.unregister(Group)
admin.site.unregister(Attachment)


def handler404(request, exception, template_name="404.html"):
    return render(
        request,
        template_name=template_name,
        status=404,
        context={"page_title": "Page non trouvée"},
    )


def handler403(request, exception, template_name="403.html"):
    return render(
        request,
        template_name=template_name,
        status=403,
        context={"page_title": "Page non trouvée"},
    )


def handler500(request, template_name="500.html"):
    return render(
        request,
        template_name=template_name,
        status=500,
        context={"page_title": "Erreur interne"},
    )


urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path("sp-", include("pages.urls", namespace="pages")),
    path("checkout/", include("checkout.urls", namespace="checkout")),
    path(route="catalog/", view=search_view, name="search"),
    path("", include("catalogue.urls")),
    path("jet/", include("jet.urls", "jet")),
    path("summernote/", include("django_summernote.urls")),
    path("", include("accounts.urls")),
    path("", include("pwa.urls")),
    path(
        "sitemap.xml",
        views.sitemap,
        {"sitemaps": SITEMAPS},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = handler404
handler403 = handler403
handler201600 = handler500

admin.site.site_header = "LAREGINA DEALS ADMIN"
admin.site.site_title = "LAREGINA DEALS ADMIN"

if settings.DEBUG:
    urlpatterns += [
        path("404", handler404, {"exception": Exception()}),
        path("403", handler403, {"exception": Exception()}),
        path("500", handler500),
    ]

checkout/forms.py
from checkout.models import Order
from django import forms


class CheckoutForm(forms.ModelForm):
    privacy = forms.BooleanField(required=True)

    def __init__(self, *args, **kwargs):
        super(CheckoutForm, self).__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs["class"] = "form-control shadown-none"

            if self.fields["shipping_country"]:
                self.fields["shipping_country"].widget.attrs.update(
                    {"class": "form-control custom-select"}
                )

        note_placehoder = (
            "Commentaires concernant votre commande, ex.: consignes de livraison."
        )
        shipping_adress_text = (
            "Votre adresse géographique, ex. : Quartier N°/Nom de la rue, etc."
        )

        self.fields["email"].widget.attrs["placeholder"] = "Entrer votre adresse email"
        self.fields["shipping_last_name"].widget.attrs[
            "placeholder"
        ] = "Entrer votre prénom"
        self.fields["shipping_first_name"].widget.attrs[
            "placeholder"
        ] = "Entrer votre nom"
        self.fields["phone"].widget.attrs["placeholder"] = "Exemple: +225xxxxxxxxx"
        self.fields["phone_two"].widget.attrs["placeholder"] = "Exemple: +225xxxxxxxxx"
        self.fields["shipping_country"].widget.attrs[
            "placeholder"
        ] = "sélection un pays"
        self.fields["shipping_city"].widget.attrs["placeholder"] = "Ville de résidence"
        self.fields["shipping_adress"].widget.attrs[
            "placeholder"
        ] = shipping_adress_text
        self.fields["shipping_zip"].widget.attrs["placeholder"] = "Code postal"
        self.fields["emailing"].widget.attrs["type"] = "checkbox"
        self.fields["privacy"].widget.attrs["type"] = "checkbox"
        self.fields["privacy"].widget.attrs["checked"] = "True"
        self.fields["privacy"].widget.attrs["class"] = "form-check"
        self.fields["note"].widget.attrs["rows"] = "5"
        self.fields["note"].widget.attrs["placeholder"] = note_placehoder

    class Meta:
        model = Order
        fields = "__all__"
        exclude = [
            "status",
            "collecte_data",
            "transaction_id",
            "distributor",
            "ip_address",
            "created_at",
            "updated_at",
        ]

checkout/views.py
import io

from cart import cart
from checkout import checkout
from checkout import tasks
from checkout.forms import CheckoutForm
from checkout.models import Order
from checkout.models import OrderItem
from cinetpay_sdk.s_d_k import Cinetpay
from django.conf import settings
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.template import Context
from django.template.loader import get_template
from django.urls import reverse
from django.urls import reverse_lazy
from django.views import generic
from django.views.decorators.csrf import csrf_exempt
from xhtml2pdf import pisa

apikey = settings.CINETPAY_API_KEY
site_id = settings.CINETPAY_SITE_ID

client = Cinetpay(apikey, site_id)


@csrf_exempt
def show_checkout(request, template="checkout/checkout.html"):
    if cart.is_empty(request):
        return HttpResponseRedirect(reverse("cart:cart"))

    if request.method == "POST":
        postdata = request.POST.copy()
        form = CheckoutForm(postdata)
        if form.is_valid():
            response = checkout.process(request)
            order_id = response.get("order_id", 0)
            payment = response.get("payment")

            if payment == 0:
                if order_id:
                    request.session["order_id"] = str(order_id)

                    sucess_url = reverse(
                        "checkout:order_success", kwargs={"order_id": order_id}
                    )
                return HttpResponseRedirect(sucess_url)

            if payment == 1:
                order = response.get("order")

                amount = order.get_order_total()
                transaction_id = order.transaction_id
                customer_name = order.get_short_name()

                NOTIFY_URL = "{% url  'cart:cart' %}"
                RETURN_URL = (
                    "{% url 'checkout:order_success' order_id=order.transaction_id %}"
                )

                data = {
                    "amount": amount,
                    "currency": "XOF",
                    "transaction_id": transaction_id,
                    "description": "Finaliser votre achat",
                    "return_url": RETURN_URL,
                    "customer_name": customer_name,
                    "notify_url": NOTIFY_URL,
                    "customer_surname": customer_name,
                }

                response = client.PaymentInitialization(data)

                PAYMENT_URL = response["data"]["payment_url"]
                return HttpResponseRedirect(PAYMENT_URL)
    else:
        if request.user.is_authenticated:
            form = CheckoutForm(instance=request.user)
        else:
            form = CheckoutForm()

    context = {
        "form": form,
        "page_title": "Paiement",
        "cart_items": cart.get_cart_items(request),
        "cart_subtotal": cart.cart_subtotal(request),
    }

    return render(request, template, context)


show_checkout = show_checkout


def order_success_view(request, order_id, template="checkout/checkout_success.html"):
    order_id = request.session.get("order_id")

    order = get_object_or_404(Order, transaction_id=order_id)
    order_items = OrderItem.objects.filter(order=order)
    tasks.send_sms_order.delay(order_id)
    context = {
        "object": order,
        "order_items": order_items,
        "page_title": "Commande validée",
    }

    return render(request, template, context)


order_success_view = order_success_view


def render_to_pdf(template_src, context_dict):
    template = get_template(template_src)
    template_src = Context({"pagesize": "A4"})
    html = template.render(context_dict)

    result = io.BytesIO()
    pdf = pisa.pisaDocument(io.BytesIO(html.encode("UTF-8")), result)
    if not pdf.err:
        response = HttpResponse(
            result.getvalue(),
            content_type="application/pdf",
        )
        response["Content-Disposition"] = 'attachment; filename="facture.pdf"'
        return response
    else:
        return HttpResponse("Erreur lors du rendu de la facture.", status=400)


def download_invoice_view(request, order_id):
    order = Order.objects.get(id=order_id)
    order_item = OrderItem.objects.filter(order=order)
    mydict = {
        "order_item": order_item,
        "object_date": order.date,
        "object_id": order.transaction_id,
        "get_full_name": order.get_full_name,
        "order_total": order.get_order_total,
        "get_shipping_delivery": order.get_shipping_delivery,
    }
    return render_to_pdf("checkout/snippet/_partials_order_invoice.html", mydict)


download_invoice_view = download_invoice_view


class TrackOrderListView(generic.ListView):
    template_name = "checkout/snippet/_partials_order_tracking.html"
    success_url = reverse_lazy("order_tracking")
    extra_context = {"page_title": "suivre votre commande"}

    def get_context_data(self, **kwargs):
        kwargs["query"] = self.request.GET.get("track", None)
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        query = self.request.GET.get("track", None)
        if query is not None:
            return Order.objects.track_order(query)
        return Order.objects.none()


track_order_view = TrackOrderListView.as_view()

templates/checkout/snippet/_partials_order_invoice.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        {% load cache static humanize %}{% get_static_prefix as STATIC_PREFIX %}
        <meta charset="UTF-8">
        {% cache 120 css_file_invoice  %}
            <link href='https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/css/bootstrap.min.css' rel='stylesheet'>
            <script type='text/javascript' src='https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/js/bootstrap.bundle.min.js'></script>
        {% endcache %}
        <style>
          ²body {
                font-family: 'Maven Pro', sans-serif;
            }

            hr {
                color: #0000004f;
                margin-top: 5px;
                margin-bottom: 5px;
            }

            .add td {
                color: #c5c4c4;
                text-transform: uppercase;
                font-size: 12px;
            }

            .content {
                font-size: 14px;
            }
        </style>
    </head>

    <body>
        <div class="container mt-5 mb-3">
            <div class="row d-flex justify-content-center">
                <div class="col-md-8">
                    <div class="card">
                        <div class="d-flex flex-row p-2">
                            <img loading="lazy" src="{{ STATIC_PREFIX }}img/invoice.jpg" class="img-fluid">
                            <div class="d-flex flex-column">
                                <a href="https://www.laregina.deals">
                                    <span class="font-weight-bold">Laregina Deals</span>
                                </a>
                            </div>
                        </div>

                        <hr>

                        <div class="address p-2">
                            <table class="table table-borderless">
                                <tbody>
                                    <tr class="add">
                                        <td>FACTURE Ref:</td>
                                    </tr>
                                    <tr class="content">
                                        <td>{{ object_id }}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>

                        <hr>

                        <div class="table-responsive p-4">
                            <table class="table table-borderless">
                                <tbody>
                                    <tr class="add">
                                        <td>Détails du paiment:</td>
                                        <td>Client facturé:</td>
                                    </tr>
                                    <tr class="content">
                                        <td class="font-weight-bold">
                                            <strong>Commandée le</strong>: {{ object_date|date }} <br>
                                            <strong> Mode de réglement</strong>:  Paiement à la livraion
                                        </td>

                                        <td class="font-weight-bold">
                                            <strong>{{ get_full_name }}</strong><br>
                                            {{ get_shipping_delivery }}
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>

                        <hr>

                        <div class="products p-2">
                            <table class="table table-borderless">
                                <tbody>
                                    <tr class="add">
                                        <td>Magasin</td>
                                        <td>Produit</td>
                                        <td>Qté</td>
                                        <td>Prix</td>
                                        <td class="text-center">Total</td>
                                    </tr>
                                    <tr class="content">
                                        {% for obj in order_item %}
                                            <td>{{ obj.product.user.store }}</td>
                                            <td>{{ obj.get_product_name|truncatewords:'2' }}</td>
                                            <td>{{ obj.quantity }}</td>
                                            <td>{{ obj.get_product_price|intcomma }}</td>
                                            <td class="text-center">{{ obj.total|intcomma }} Fr</td>
                                        {% endfor %}
                                    </tr>
                                </tbody>
                            </table>
                        </div>

                        <hr>

                        <div class="products p-2">
                            <table class="table table-borderless">
                                <tbody>
                                    <tr class="add">
                                        <td></td>
                                        <td>Frais de livraison (Gratuite)</td>
                                        <td class="text-center">Total</td>
                                    </tr>
                                    <tr class="content">
                                        <td></td>
                                        <td>1500 Fr</td>
                                        <td class="text-center">{{ order_total|intcomma }} Fr</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

templates/checkout/snippet/_partials_order_tracking.html
{% extends "base.html" %}

{% block content %}
    {% include "includes/partials/_partials_breadcrumb.html" %}
    {% url 'order_tracking' as tracking %}

    <div class="ps-order-tracking p-5">
        <div class="container">
            <div class="row justify-content-center mt-5 align-items-center">
                <div class="col-md-8">
                    {% if not query %}
                        <div class="ps-section__header pb-5">
                            <h4>Suivre l'état de votre commande</h4>
                            <p class="small">Pour suivre votre commande, veuillez entrer votre <strong>N° de la commande</strong> dans
                            la case ci-dessous et appuyez sur le bouton « Suivi de commande ».
                            Cela vous a été remis sur votre reçu et dans l'e-mail de confirmation que vous auriez dû recevoir.</p>
                        </div>

                        <div class="ps-section__content">
                            <form role='search' accept-charset="utf-8" class="ps-form--order-tracking" action="{{ tracking }}" method="get">
                                <div class="form-group">
                                    <label>N° de la commande</label>
                                    <input required="True" id='input-search' name='track' class="form-control" type="search"
                                    placeholder="Entrer le N° de la commande qui vous a été fourni" value="{{ request.GET.track }}">
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="ps-btn btn-primary ps-btn--fullwidth">Suivi de commande</button>
                                </div>

                                <!-- connexion url -->
                                <div class="text-center w-100 pt-3 pb-3">
                                    <span class="font-weight-bold text-muted">
                                        <a href="#">
                                            <span>Vous avez oubliez votre N° de Commande ?</span>
                                        </a>
                                    </span>
                                </div>
                            </form>
                        </div>
                    {% else %}
                        {% include "checkout/snippet/_partials_tracking_result.html" %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/checkout/snippet/_partials_tracking_result.html
<style>

	/* Timeline holder */
	ul.timeline {
		list-style-type: none;
		position: relative;
		padding-left: 1.5rem;
	}

	/* Timeline vertical line */
	ul.timeline:before {
		content: ' ';
		background: #fff;
		display: inline-block;
		position: absolute;
		left: 16px;
		width: 4px;
		height: 100%;
		z-index: 400;
		border-radius: 1rem;
	}

	li.timeline-item {
		margin: 20px 0;
	}

	/* Timeline item arrow */
	.timeline-arrow {
		border-top: 0.5rem solid transparent;
		border-right: 0.5rem solid #fff;
		border-bottom: 0.5rem solid transparent;
		display: block;
		position: absolute;
		left: 2rem;
	}

	/* Timeline item circle marker */
	li.timeline-item::before {
		content: ' ';
		background: #ddd;
		display: inline-block;
		position: absolute;
		border-radius: 50%;
		border: 3px solid #fff;
		left: 11px;
		width: 14px;
		height: 14px;
		z-index: 400;
		box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);
	}
</style>

{% url "order_tracking" as order_tracking_id %}
{% url "catalogue:product_list" as product_list %}

<div class="ps-section__content">
	<h3>Statut de la commande</h3>
	<div class="card shadow-sm">
		<div class="card-body p-5">
			{% if object_list %}
				{% for object in object_list %}
					<p class="text-center bg-light py-4 my-3">
						Numéro de commande: <strong class="card-title">{{ object }}</strong>
					</p>

					<ul class="timeline">
						<li class="timeline-item bg-white rounded ml-3 p-4 shadow">
							<div class="timeline-arrow"></div>
							<h2 class="h5 mb-0">{{ object.status|upper }}</h2>
						</li>
					</ul>
				{% endfor %}
			{% else %}
				<p class="text-center bg-light py-4 my-3">
					Ce numéro de commande n'existe pas.
				</p>
			{% endif %}
		</div>

		<div class="card-footer text-muted text-center bg-transparent p-4">
			<a href="#" class="ps-btn btn btn-md float-left">
		    <span>Annuler ma commande</span></a>

		    <a href="{{ order_tracking_id }}" class="ps-btn btn btn-md">
		    <span>Suivre une autre commande</span></a>

		    <a href="{{ product_list }}" class="ps-btn btn btn-md float-right">
		    <span>Continuer vos achats</span></a>
		</div>
	</div>
</div>