accounts/urls.py
from accounts import views
from django.urls import path
from django.urls import include


urlpatterns = [
    path(
        "customer/account/",
        include(
            (
                [
                    path(
                        route="signup/",
                        view=views.account_signup_view,
                        name="account_signup",
                    ),
                    path(
                        route="login/",
                        view=views.account_login_view,
                        name="account_login",
                    ),
                    path(
                        route="reset-password/",
                        view=views.account_request_password_reset_view,
                        name="account_reset_password",
                    ),
                    path(
                        route="reset-password/<uidb64>/<token>/",
                        view=views.account_request_password_reset_view,
                        name="account_reset_password",
                    ),
                    path(
                        route="set-new-password/<uidb64>/<token>/",
                        view=views.account_set_new_password_view,
                        name="set_new_password",
                    ),
                    path(
                        route="logout/",
                        view=views.account_logout_view,
                        name="account_logout",
                    ),
                ],
                "accounts",
            ),
            namespace="auth_views",
        ),
    ),
    path(
        "customer/",
        include(
            (
                [
                    path(
                        route="account/index/",
                        view=views.dashboard_view,
                        name="profile",
                    ),
                    path(
                        route="order/index/",
                        view=views.order_list_view,
                        name="order_list",
                    ),
                    path(
                        route="order/detail/<int:pk>/",
                        view=views.order_detail_view,
                        name="order_detail",
                    ),
                    path(
                        route="settings/<str:slug>/",
                        view=views.settings_view,
                        name="update",
                    ),
                ],
                "accounts",
            ),
            namespace="dashboard_users",
        ),
    ),
    path(
        "sp-marketplace-delivery/",
        include(
            (
                [
                    path(
                        route="register/",
                        view=views.distributor_register_view,
                        name="delivery_register",
                    ),
                    path(
                        route="success/<int:delivery_id>/",
                        view=views.distributor_register_success_view,
                        name="delivery_register_success",
                    ),
                ],
                "accounts",
            ),
            namespace="delivery",
        ),
    ),
]

catalogue/urls.py
from cart.views import shopcart
from catalogue import views as catalogue_views
from category.views import category_detail_view
from django.urls import include
from django.urls import path
from pages import views as pages_views


urlpatterns = [
    path(route="", view=catalogue_views.home_view, name="home"),
    path(
        "cart/index/",
        include(
            (
                [
                    path(route="", view=shopcart, name="cart"),
                ],
                "catalogue",
            ),
            "cart",
        ),
    ),
    path(
        "",
        include(
            (
                [
                    path(
                        route="produit/",
                        view=catalogue_views.product_list_view,
                        name="product_list",
                    ),
                    path(
                        route="ps-<str:slug>-<int:pk>/",
                        view=catalogue_views.show_product,
                        name="product_detail",
                    ),
                ],
                "catalogue",
            ),
            namespace="catalogue",
        ),
    ),
    path(
        "",
        include(
            (
                [
                    path(
                        route="<str:slug>/",
                        view=category_detail_view,
                        name="category_detail",
                    ),
                ],
                "catalogue",
            ),
            "category",
        ),
    ),
    path(
        "avis-cliens/",
        include(
            (
                [
                    path(
                        route="<str:slug>/",
                        view=catalogue_views.add_review,
                        name="add_product_review",
                    ),
                ],
                "catalogue",
            ),
            namespace="reviews",
        ),
    ),
    path(
        "promotion/",
        include(
            (
                [
                    path(
                        route="<str:slug>/",
                        view=pages_views.promotion_detail,
                        name="promotion_detail",
                    ),
                    path(
                        route="destockages/list/",
                        view=pages_views.destockage_list_view,
                        name="promotion_destockage_list",
                    ),
                    path(
                        route="flash-sales/list/",
                        view=pages_views.sales_flash_list_view,
                        name="promotion_sales_flash_list",
                    ),
                    path(
                        route="nouveautes/list/",
                        view=pages_views.news_arrivals_list_view,
                        name="promotion_news_arrival_list",
                    ),
                ],
                "catalogue",
            ),
            namespace="promotion",
        ),
    ),
]

core/urls.py
from core.sitemap import SITEMAPS
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.models import Group
from django.contrib.sitemaps import views
from django.contrib.sites.models import Site
from django.shortcuts import render
from django.urls import include
from django.urls import path
from django.views.generic import TemplateView
from django_summernote.models import Attachment
from search.views import search_view

admin.site.unregister(Site)
admin.site.unregister(Group)
admin.site.unregister(Attachment)


def handler404(request, exception, template_name="404.html"):
    return render(
        request,
        template_name=template_name,
        status=404,
        context={"page_title": "Page non trouvée"},
    )


def handler403(request, exception, template_name="403.html"):
    return render(
        request,
        template_name=template_name,
        status=403,
        context={"page_title": "Page non trouvée"},
    )


def handler500(request, template_name="500.html"):
    return render(
        request,
        template_name=template_name,
        status=500,
        context={"page_title": "Erreur interne"},
    )


urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path("sp-", include("pages.urls", namespace="pages")),
    path("checkout/", include("checkout.urls", namespace="checkout")),
    path(route="catalog/", view=search_view, name="search"),
    path("", include("catalogue.urls")),
    path("jet/", include("jet.urls", "jet")),
    path("summernote/", include("django_summernote.urls")),
    path("", include("accounts.urls")),
    path("", include("pwa.urls")),
    path(
        "sitemap.xml",
        views.sitemap,
        {"sitemaps": SITEMAPS},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = handler404
handler403 = handler403
handler201600 = handler500

admin.site.site_header = "LAREGINA DEALS ADMIN"
admin.site.site_title = "LAREGINA DEALS ADMIN"

if settings.DEBUG:
    urlpatterns += [
        path("404", handler404, {"exception": Exception()}),
        path("403", handler403, {"exception": Exception()}),
        path("500", handler500),
    ]

pages/urls.py
from django.conf import settings
from django.urls import path
from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView
from pages.views import contact_view

CACHE_TTL = getattr(settings, "CACHE_TTL", settings.CACHE_TIMEOUT)

app_name = "pages"
urlpatterns = [
    path(route="contactez-nous/", view=contact_view, name="contact"),
    path(
        "qui-sommes-nous/",
        cache_page(CACHE_TTL)(
            TemplateView.as_view(
                extra_context={
                    "page_title": "À propos de nous",
                    "page_description": "Qui sommes-nous ?",
                },
                template_name="pages/about-us.html",
            )
        ),
        name="about-us",
    ),
    path(
        "questions-frequement-posees/",
        cache_page(CACHE_TTL)(
            TemplateView.as_view(
                extra_context={
                    "page_title": "FAQs : Questions fréquemment posées",
                    "page_description": "Questions fréquemment posées",
                },
                template_name="pages/faqs.html",
            )
        ),
        name="faqs",
    ),
    path(
        "condition-generale-utilisation/",
        cache_page(CACHE_TTL)(
            TemplateView.as_view(
                extra_context={
                    "page_title": "Conditions Générales d'Utilisation",
                    "page_description": "Conditions Générales d'Utilisation",
                },
                template_name="pages/cgu.html",
            )
        ),
        name="cgu",
    ),
    path(
        "politique-de-confidentialite/",
        cache_page(CACHE_TTL)(
            TemplateView.as_view(
                extra_context={
                    "page_title": "Politique de Confidentialité",
                    "page_description": "Politique de Confidentialité",
                },
                template_name="pages/policy.html",
            )
        ),
        name="policy",
    ),
    path(
        "politique-de-retour/",
        cache_page(CACHE_TTL)(
            TemplateView.as_view(
                extra_context={
                    "page_title": "Politique de retour",
                    "page_description": "Politique de retour",
                },
                template_name="pages/return.html",
            )
        ),
        name="return",
    ),
]

catalogue/forms.py
# catalogue.forms.py
from category.models import Category
from django import forms
from django.forms.models import inlineformset_factory
from django_summernote.widgets import SummernoteWidget

from .models import Product
from .models import ProductAttributeValue
from .models import ProductImage


class ProductAdminForm(forms.ModelForm):
    category = forms.ModelChoiceField(
        empty_label=None,
        required=True,
        label="Choisir une catégorie",
        queryset=Category.objects.all(),
    )

    class Meta:
        model = Product
        exclude = [
            "user",
            "quantity",
            "slug",
            "updated_at",
            "is_external",
            "created_at",
            "timestamp",
        ]

        widgets = {"description": SummernoteWidget()}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs[
                "class"
            ] = "form-control shadow-none rounded-0"

            if self.fields["is_active"]:
                self.fields["is_active"].widget.attrs.update(
                    {"class": "form-check-input shadow-none"}
                )

        self.fields["name"].widget.attrs["placeholder"] = "Entrer le nom du produit"
        self.fields["price"].widget.attrs[
            "placeholder"
        ] = "Entrer le prix de vente du produit"
        self.fields["keywords"].widget.attrs[
            "placeholder"
        ] = "Ajouter quelques mots-clés (facultatif)"

    def clean(self):
        cleaned_data = super().clean()
        price = cleaned_data.get("price")

        if price <= 100:
            msg = "Le prix doit être supérieur à 100 Fr !"
            self.errors["price"] = self.error_class([msg])
        return cleaned_data


class ProductImageForm(forms.ModelForm):
    image = forms.ImageField(label="Ajouter des images", required=True)

    class Meta:
        model = ProductImage
        fields = ("image",)


class ProductAttributeValueForm(forms.ModelForm):
    size = forms.MultipleChoiceField(
        label="Sélectionner les tailles", choices=ProductAttributeValue.SIZE_CHOICES
    )

    class Meta:
        model = ProductAttributeValue
        fields = ["size"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs[
                "class"
            ] = "form-control shadow-none rounded-0"


ProductCreateFormSet = inlineformset_factory(
    parent_model=Product,
    model=ProductImage,
    form=ProductImageForm,
    fields=["product", "image"],
    exclude=["timestamp", "updated"],
    can_delete=False,
    extra=4,
    max_num=4,
)

ProductAttributeCreateFormset = inlineformset_factory(
    parent_model=Product,
    model=ProductAttributeValue,
    form=ProductAttributeValueForm,
    fields=["product", "size"],
    can_delete=False,
    extra=1,
    max_num=1,
)


class ProductAddToCartForm(forms.Form):
    quantity = forms.IntegerField(
        widget=forms.TextInput(
            attrs={"type": "hidden", "value": "1", "class": "form-control"}
        ),
        error_messages={"invalid": " Veuillez entrer une quantité valide."},
        min_value=1,
    )
    slug = forms.CharField(widget=forms.HiddenInput())

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        super().__init__(*args, **kwargs)

    def clean(self):
        if self.request:
            if not self.request.session.test_cookie_worked():
                raise forms.ValidationError("Les cookies doivent être activés.")
        return self.cleaned_data

templates/catalogue/product_detail.html
{% extends "base.html" %}
{% load static cache humanize mptt_tags crispy_forms_tags catalogue_tags pages_tags %}

{% block content %}

    {% full_tree_for_model category.Category as category %}
    {% url "delivery:delivery_register" as delivery_register %}

    <div class="ps-breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li>
                    <a class="text-capitalize" href="{{ home_url }}">
                        <i class="fa fa-home fw-2x text-success"></i>
                    </a>
                </li>
                {% if object.category.parent %}
                    <li>
                        <a href="{{ object.category.parent.get_absolute_url }}">
                            {{ object.category.get_ancestors|tree_path|lower }}
                        </a>
                    </li>
                {% endif %}
                {% if object.category.name %}
                    <li>
                        <a href="{{ object.category.get_absolute_url }}">
                            {{ object.category.name|lower }}
                        </a>
                    </li>
                {% endif %}

                <li>{{ object.name|capfirst|lower|safe }}</li>
            </ul>
        </div>
    </div>

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-block {{ message.tags }} alert-dismissible font-weight-bold" role="alert">
                {{ message|safe }}
                <button class="close" type="button" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endif %}

    <div class="ps-page--product">
        <div class="container">
            <div class="ps-page__container">
                <div class="ps-page__left">
                    <div class="ps-product--detail ps-product--fullwidth">
                        <div class="ps-product__header">

                            {% include "catalogue/partials/_partials_product_image.html" with object=object %}

                            <div class="ps-product__info">
                                <h1>{{ object.name|safe }}</h1>
                                <div class="ps-product__meta">
                                    <div class="ps-product__rating">
                                        <select class="ps-rating" data-read-only="true">
                                            <option value="1">1</option>
                                            <option value="1">2</option>
                                            <option value="1">3</option>
                                            <option value="1">4</option>
                                            <option value="2">5</option>
                                        </select>
                                        <span>({{ object.countreview|safe }} avis)</span>
                                    </div>
                                </div>
                                <h4 class="ps-product__price sale">
                                    {% if object.get_vouchers %}
                                        {{ object.get_product_price|intcomma }} Fr
                                        <del> {{ object.price|intcomma }} Fr</del>
                                        <small> ( -{{ object.get_vouchers }}%)</small>
                                    {% else %}
                                        {{ object.price|intcomma }} Fr
                                    {% endif %}
                                </h4>

                                <div class="ps-product__desc">
                                    {% if object.user.store %}
                                        <p>Vendu par: <a href="{{ object.user.get_absolute_url }}">
                                            <strong> {{ object.user.store }}</strong></a>
                                        </p>
                                    {% endif %}
                                </div>

                                {% if object.attributes.exists  %}
                                    <div class="ps-product__variations">
                                        <figure>
                                            <figcaption>
                                                <strong class="text-uppercase text-success">tailles disponibles</strong>
                                            </figcaption>

                                            {% for size in object.attributes %}
                                                <div class="ps-variant ps-variant--size">
                                                    <span class="ps-variant__tooltip">{{ size.size }}</span>
                                                    <span class="ps-variant__size">{{ size.size }}</span>
                                                </div>
                                            {% endfor %}
                                        </figure>
                                    </div>
                                {% endif %}

                                {% include "cart/snippet/form.html" with product=object %}

                                <div class="ps-product__specification">
                                    {% url 'pages:contact' as contact %}
                                    <a class="report" href="{{ contact }}">Signaler un abus</a>

                                    <p class="categories">
                                        <strong> Catégorie{{ category.count|pluralize }}:</strong>
                                        <a href="{{ object.category.get_absolute_url }}">
                                            {{ object.category.name|safe }}
                                        </a>
                                    </p>
                                </div>

                                <div class="ps-product__sharing">
                                    <a class="facebook" href="https://www.facebook.com/sharer.php?u=https://{{ request.get_host }}{{ object.get_absolute_url|urlencode }}" onclick="window.open(this.href,'mywin','left=20,top=20,width=500,height=500,toolbar=1,resizable=0'); return false;">
                                        <i class="fa fa-facebook"></i>
                                    </a>

                                    <a style="background-color:#fcb800" target="_blank" class="whatsapp" href="https://wa.me/?text=Bonjour, ce produit https://{{ request.get_host }}{{ object.get_absolute_url|urlencode }} peut t'intéresser.">
                                        <i class="fa fa-whatsapp"></i>
                                    </a>
                                </div>
                            </div>
                        </div>

                        <div class="ps-product__content ps-tab-root">
                            <ul class="ps-tab-list">
                                <li class="active"><a href="#tab-1">Description</a></li>
                                <li><a href="#tab-2">Vendeur</a></li>
                                <li><a href="#tab-3">Avis client ({{ object.countreview|safe }})</a></li>
                            </ul>

                            <div class="ps-tabs">
                                <div class="ps-tab active" id="tab-1">
                                    <div class="ps-document">
                                        {{ object.description|safe }}
                                    </div>
                                </div>

                                <div class="ps-tab" id="tab-2">
                                    {% if object.user.store %}
                                        <h4>{{ object.user.store|upper }}</h4>
                                        <p>{{ object.user.store_description|safe }}</p>
                                        <a href="{{ object.user.get_absolute_url }}">
                                            Voir le magasin de <strong>{{ object.user.store }}</strong>
                                        </a>
                                    {% else %}
                                        Produit vendu par l'entreprise.
                                    {% endif %}
                                </div>

                                <div class="ps-tab" id="tab-3">
                                    <div class="row">
                                        {% include "includes/partials/_partials_product_review.html" %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="ps-page__right">
                    <!-- delivery information -->
                    <aside class="widget widget_product widget_features mb-3">
                        <p><i class="icon-3d-rotate"></i> Retour gratuit sous 7 jours si éligible</p>
                        <p><i class="icon-receipt"></i> Le fournisseur donne des factures pour ce produit.</p>
                        <p><i class="icon-credit-card"></i> Payer en ligne ou lors de la réception de marchandises</p>
                    </aside>

                    {% if request.user.is_authenticated and request.user.is_buyer or not request.user.is_authenticated and not request.user.is_superuser and not request.user.is_seller %}
                        <aside class="widget widget_sell-on-site mb-3">
                            {% url "auth_views:account_signup" as account_signup %}
                            <p>
                                <i class="icon-store"></i> Vendez sur LaRegina ?
                                <a href="{{ account_signup }}" target="_blank">
                                    Ouvrez votre boutique maintenant !
                                </a>
                            </p>
                        </aside>
                    {% endif %}

                    <!--
                    <aside class="widget widget_sell-on-site">
                        <a class="ps-collection" href="{{ delivery_register }}">
                            <img loading="lazy" src="{{ STATIC_PREFIX }}img/laregina-distributeur-homepage.jpg" alt="distributeur-produit-laregina">
                        </a>
                    </aside>
                     -->
                </div>
            </div>

            {% best_selling_products 20 %}

            <!-- produit recommendé -->
            {% if recommended_product %}
                {% product_list recommended_product 'Produits récommandés pour vous' %}
            {% endif %}

            <!-- produit similaire  -->
            {% if related_product %}
                {% product_list related_product 'Produits de la même catégorie' %}
            {% endif %}

            <!-- product recently viewed -->
            {% if recently_viewed %}
                {% product_list recently_viewed 'Vus récemment' %}
            {% endif %}
        </div>
    </div>
{% endblock content %}

templates/catalogue/product_list.html
{% extends "base.html" %}
{% load mptt_tags catalogue_tags pages_tags %}

{% block content %}
{% url "home" as home_url %}

{% if request.resolver_match.url_name == 'product_list' %}

{% include "includes/partials/_partials_breadcrumb.html" %}

{% elif request.resolver_match.url_name == 'category_detail' %}
    <div class="ps-breadcrumb">
        <div class="ps-container">
            <ul class="breadcrumb">
                <li>
                    <a class="text-capitalize" href="{{ home_url }}">
                        <i class="fa fa-home fw-2x text-success"></i>
                    </a>
                </li>
                {% if object.category.parent %}
                    <li>
                        <a href="{{ object.category.parent.get_absolute_url }}">
                            {{ object.category.get_ancestors|tree_path|lower }}
                        </a>
                    </li>
                {% endif %}
                {% if object.category.name %}
                    <li>
                        <a href="{{ object.category.get_absolute_url }}">
                            {{ object.category.name|lower }}
                        </a>
                    </li>
                {% endif %}

                <li>{{ object.name|capfirst|striptags|safe }}</li>
            </ul>
        </div>
    </div>
{% endif %}

<div class="ps-page--shop pt-2">
    <div class="container">

        {% if object.image %}
            <div class="ps-carousel--nav-inside py-3 mb-4">
                <img loading="lazy" class="w-100" src="{{ object.get_image_url }}" alt="{{ object.name|slugify }}">
            </div>
        {% endif %}

        {% if object.promotions_category %}
            {% for promotion in object.promotions_category %}
                <section class="ps-block--container-hightlight">
                    <div class="ps-section__header pb-3">
                        <h3>{{ promotion.campaign.name|title }}</h3>
                    </div>
                    <div class="ps-section__content py-3 mb-3">
                        <div class="ps-carousel--nav owl-slider" data-owl-auto="true" data-owl-loop="true" data-owl-speed="5000" data-owl-gap="30" data-owl-nav="false" data-owl-dots="false" data-owl-item="5" data-owl-item-xs="2" data-owl-item-sm="3" data-owl-item-md="4" data-owl-item-lg="4" data-owl-item-xl="5" data-owl-duration="1000" data-owl-mousedrag="on">
                            {% for object in object.promotions_category %}
                                {% for product in object.products.all %}
                                    {% include "catalogue/snippet/_snippet_product.html" with instance=product %}
                                {% endfor %}
                            {% endfor %}
                        </div>
                    </div>
                </section>
            {% endfor %}
        {% endif %}

        <div class="ps-layout--shop border-bottom mb-2">
            {% block _content_ %}
                {% include "catalogue/partials/_partials_shop.html" with object=object %}
            {% endblock _content_ %}
        </div>

        {% best_selling_products 20 %}

        {% if product_recommended %}
            <div class="ps-block--container-hightlight mt-4 pb-3">
                <div class="ps-section__header">
                    <h3>Vus récemment</h3>
                </div>
                <div class="ps-section__content">
                    <div class="ps-carousel--nav owl-slider" data-owl-auto="true" data-owl-loop="true" data-owl-speed="5000" data-owl-gap="30" data-owl-nav="false" data-owl-dots="false" data-owl-item="5" data-owl-item-xs="2" data-owl-item-sm="3" data-owl-item-md="4" data-owl-item-lg="4" data-owl-item-xl="5" data-owl-duration="1000" data-owl-mousedrag="on">
                        {% for product in product_recommended %}
                            {% include "catalogue/snippet/_snippet_product.html" with instance=product %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
</div>
{% endblock content %}